const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=__dirname,data=path.join(root,'data','portfolio.json');
const stocks=[['AAPL','Apple'],['MSFT','Microsoft'],['NVDA','NVIDIA'],['TSLA','Tesla'],['AMZN','Amazon']];
const base={cash:10000,positions:[],trades:[]};
function read(){fs.mkdirSync(path.dirname(data),{recursive:true});if(!fs.existsSync(data))fs.writeFileSync(data,JSON.stringify(base));return JSON.parse(fs.readFileSync(data))}function save(x){fs.writeFileSync(data,JSON.stringify(x))}
function out(r,n,x){r.writeHead(n,{'Content-Type':'application/json'});r.end(JSON.stringify(x))}
async function quotes(){return Promise.all(stocks.map(async([symbol,name])=>{let r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${symbol}?range=5d&interval=1d`);let x=(await r.json()).chart.result[0],p=x.indicators.quote[0].close.filter(Boolean),price=p.at(-1),previous=x.meta.previousClose||p.at(-2)||price;return{symbol,name,price,changePercent:(price-previous)/previous*100}}))}
async function portfolio(){let p=read(),q=await quotes();p.positions=p.positions.map(x=>{let price=q.find(y=>y.symbol===x.symbol)?.price||x.averagePrice,m=price*x.quantity;return{...x,marketValue:m,unrealizedGain:m-x.costBasis}});return p}
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css'};
http.createServer(async(req,res)=>{try{if(req.url==='/api/quotes')return out(res,200,await quotes());if(req.url==='/api/portfolio')return out(res,200,await portfolio());if(req.url==='/api/trades'&&req.method==='POST'){let body='';for await(const c of req)body+=c;let{symbol,quantity}=JSON.parse(body),q=(await quotes()).find(x=>x.symbol===symbol),total=q.price*quantity,p=read();if(!q||!Number.isInteger(quantity)||quantity<1)return out(res,400,{error:'Ordine non valido'});if(total>p.cash)return out(res,400,{error:'Liquidità virtuale insufficiente'});p.cash-=total;let pos=p.positions.find(x=>x.symbol===symbol);if(pos){pos.averagePrice=(pos.costBasis+total)/(pos.quantity+quantity);pos.quantity+=quantity;pos.costBasis+=total}else p.positions.push({symbol,quantity,averagePrice:q.price,costBasis:total});p.trades.unshift({type:'buy',symbol,quantity,total,date:new Date().toISOString()});save(p);return out(res,200,await portfolio())}let file=path.join(root,req.url==='/'?'index.html':req.url.split('?')[0]);if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'text/plain'});fs.createReadStream(file).pipe(res)}catch(e){out(res,500,{error:e.message})}}).listen(3000,()=>console.log('http://localhost:3000'));
